global:
  scrape_interval: 5s
  evaluation_interval: 10s

rule_files:
  - "alert.rules"
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "host.docker.internal:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "app"
    static_configs:
      - targets: ["host.docker.internal:4000"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["host.docker.internal:9200"]
